export const SET_FIRST_NAME = 'SET_FIRST_NAME';
export const SET_SURNAME = 'SET_SURNAME';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_HOURS = 'SET_HOURS';
export const SET_PART_OF_GROUP_ID = 'SET_PART_OF_GROUP_ID';
export const SET_ADMIN_OF_GROUP_ID = 'SET_ADMIN_OF_GROUP_ID';
export const SET_EVENTS_IDS = 'SET_EVENTS_IDS';
