export const actionTypes = {
  SET_FIRST_NAME: "SET_FIRST_NAME",
  SET_SURNAME: "SET_SURNAME",
  SET_USERNAME: "SET_USERNAME",
  SET_HOURS: "SET_HOURS",
  SET_PART_OF_GROUP_ID: "SET_PART_OF_GROUP_ID",
  SET_ADMIN_OF_GROUP_ID: "SET_ADMIN_OF_GROUP_ID",
  SET_EVENTS_IDS: "SET_EVENTS_IDS",
};
